### ISSUE TITLE
No items in "Laatste Journaals"

### ISSUE THREAD

**Issue by everhardt** [ErwinJunge/XBMC-plugin.video.nos#5]
Since a few of weeks there are no listings anymore under "Laatste Journaals". The other two items ("Jeugdjournaal" and "Journaal op 3") are working fine. What could be wrong?

**Comment by dewitweb** [comment]
Hi, 
First, thanks for the great app so far. But recently "Laatste Journaals" gives me an error in script. i am using version 3.3.1 of the nos app.
