### ISSUE TITLE
NOS App stopped working

### ISSUE THREAD

**Issue by eagleye50** [ErwinJunge/XBMC-plugin.video.nos#8]
Hello,

The NOS app on Kodi that I use to watch the latest broadcasts of the NOS 8-uur journaal suddenly stopped working. I could see the broadcast of April 6th but that days after that day the list of available broadcasts is not updated anymore. I use Kodi Isengard which is installed on my QNAP NAS HS-251.

Kindest regards,

Joop.

**Comment by eagleye50** [comment]
It looks like the problem is over. Since a few days the app working normal again.

**Comment by ErwinJunge** [comment]
Sorry for the late reply, I've been a bit busy with other things. The issue was that the api from NOS that I use wasn't updated by the people working at NOS. Even so, thanks for the bug report. It's really appreciated!
